---
abstract: 'simple enchantment over lib::abs '
author:
  - 'grian <grian@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: lib-deep
no_index:
  directory:
    - t
    - inc
requires:
  lib::abs: 0.01
version: 0.90
